select * from PAYMENT where TYPE_ID = (select ID from PAYMENTTYPE where NAME = 'MONTHLY');
select * from MARK where SUBJECT_ID = (select distinct ID from SUBJECT where NAME = 'Art');
select (STUDENT.NAME, STUDENT.GROUPNUMBER, STUDENT.ID, STUDENT.BIRTHDAY) from STUDENT, PAYMENTTYPE where PAYMENTTYPE.NAME= 'WEEKLY';
select (STUDENT.NAME, STUDENT.GROUPNUMBER, STUDENT.ID, STUDENT.BIRTHDAY) from STUDENT, MARK where SUBJECT_ID = (select ID from SUBJECT where STUDENT.NAME = 'Math');