select * from PAYMENT where TYPE_ID = (select ID from PAYMENTTYPE where NAME = 'MONTHLY');
select * from MARK where SUBJECT_ID = (select ID from SUBJECT where NAME = 'Art');
select (STUDENT.NAME, STUDENT.GROUPNUMBER, STUDENT.ID,  PAYMENT.TYPE_ID) from STUDENT, PAYMENT where PAYMENT.TYPE_ID= 2;
select (STUDENT.NAME, STUDENT.GROUPNUMBER, STUDENT.ID, STUDENT.BIRTHDAY) from STUDENT inner join MARK where SUBJECT_ID = (select ID from SUBJECT where SUBJECT.NAME = 'Math');