select MAX(BIRTHDAY) from STUDENT;
select MIN(PAYMENT_DATE ) from PAYMENT;
select AVG(MARK) from MARK where SUBJECT_ID = (SELECT ID from SUBJECT where SUBJECT.NAME = 'Math');
select MIN(AMOUNT) from PAYMENT where PAYMENT.TYPE_ID = (SELECT ID from PAYMENTTYPE where NAME = 'WEEKLY');